- job_name: Pull Request Body Changer
  event_method: pull_request
  repositories:
    - YotpoLtd/yotpo-email-templates
  job_class: PullRequestJob
- job_name: Pull Request Assignee Verifier
  event_method: pull_request
  repositories: :all
