- name: Pull Request Body Changer
  event: pull_request
  repositories:
    - YotpoLtd/yotpo-email-templates
  job_class: PullRequestJob
- name: Push Commit Format Verifier
  event: push
  inactive: true
  repositories: :all
